secret: 2876cb147697052eec5b3cdb56211681
siteToken: site-token
database: postgres://tofutf-postgresql?user=postgres
databasePasswordFromSecret:
  name: tofutf-postgresql
  key: postgres-password
postgres:
  enabled: true
  database: tofutf
