name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
      - name: Vet check
        run: make vet
      - name: Test
        run: make test
      # - name: Add hosts to /etc/hosts
      #   run: |
      #     # API tests create webhooks on github.com, and github.com mandates
      #     # that the webhook endpoint cannot be 'localhost', so we create a host
      #     # entry to dupe github
      #     sudo echo "127.0.0.1 otf.local" | sudo tee -a /etc/hosts
      # - name: API tests
      #   run: make go-tfe-tests
      #   env:
      #     # go-tfe tests require a valid github oauth token be set with which
      #     # to create a webhook on a github repo
      #     OAUTH_CLIENT_GITHUB_TOKEN: ${{ secrets.GO_TFE_OAUTH_CLIENT_GITHUB_TOKEN }}
      #     GITHUB_POLICY_SET_IDENTIFIER: leg100/go-tfe-webhooks
      # - name: Tests
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      #   run: make test
      # - name: Archive browser screenshots
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: e2e-screenshots
      #     path: internal/integration/screenshots/**/*.png
